kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-image
  template:
    metadata:
      labels:
        app: react-image
    spec:
      containers:
      - name: react-image
        image: yamanjkk/react-image
        ports:
        - containerPort: 80