apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: react-image
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 32000
  selector:
    app: react-image